{
 "title": "Advanced",
 "tags": [ "2024.2" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "by",
    "label": "by",
    "query": "Instance : instance,Cluster : cluster,DC : dc,Shard : instance\\,shard"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=\"$cluster\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   {
    "name": "classes",
    "label": "classes",
    "query": "label_values(scylla_io_queue_delay,class)"
   },
   {
    "name": "sg",
    "label": "group",
    "query": "label_values(scylla_scheduler_time_spent_on_task_quota_violations_ms,group)"
   },
   {
    "name": "iogroup",
    "label": "iogroup",
    "query": "label_values(scylla_io_queue_consumption,iogroup)"
   },
   {
    "name": "domain",
    "label": "domain",
    "query": "label_values(scylla_rpc_client_count,domain)"
   },
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   {
    "name": "topbottom",
    "label": "Filter",
    "query": "top : topk,bottom : bottomk,limit : limitk"
   },
   {
    "name": "filter_limit",
    "query": "0, 5, 10, 20, 50, 100, 256, 500, 1000, 10000"
   },
   { "name": "scylla_version", "query": "2024.2" },
   { "name": "monitoring_version", "query": "4.12.1" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "The cluster status",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max(scylla_manager_scheduler_run_indicator{type=~\"repair\",cluster=\"$cluster\"})*2 + max(scylla_manager_scheduler_run_indicator{type=~\"backup\",cluster=\"$cluster\"}))>0",
     "legendFormat": "Manager"
    },
    {
     "expr": "count(scrape_samples_scraped{job=~\"$cluster|$^\", cluster=\"$cluster\"}==0) > 0",
     "legendFormat": "Unreachable"
    },
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}<3)>0",
     "legendFormat": "Joining"
    },
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}>3)>0",
     "legendFormat": "Leaving"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "The number of nodes configured in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{job=~\"$cluster|$^\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(scylla_node_operation_mode!=3) >0",
     "legendFormat": "Inactive"
    },
    {
     "expr": "(count(scrape_samples_scraped{job=~\"$cluster|$^\", cluster=\"$cluster\"}==0) OR vector(0))>0",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "# Cores",
   "type": "stat",
   "description": "The number of CPU Cores actively used in the cluster.\n\nNote that CPU Cores that belongs to unreachable nodes, or nodes that are not in normal mode, will not be counted",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count(scylla_reactor_utilization{job=~\"$cluster|$^\", cluster=\"$cluster\"}) by (instance) * on(instance) (scylla_node_operation_mode{job=~\"$cluster|$^\", cluster=\"$cluster\"}== bool 3))"
    }
   ]
  },
  {
   "title": "# Tables",
   "type": "stat",
   "description": "The number of tables",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(scylla_column_family_cache_hit_rate{cluster=\"$cluster\", ks!~\"system.*\"}) by(cf, ks))"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) + (sum(rate(scylla_thrift_served{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Avg Write",
   "type": "stat",
   "description": "Average Write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(wlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "P99 Write",
   "type": "stat",
   "description": "P99 write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(wlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "Avg Read",
   "type": "stat",
   "description": "Average Read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "description": "P99 read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(rate(scylla_scheduler_runtime_ms{group=~\"sl:.*|commitlog\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by (group)/10)"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The rate of timeouts (read and write).\n\nTimeouts are an indication of an overloaded system",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0)) + (sum(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">IO Queue Information</h1>"
  },
  {
   "title": "I/O Group consumption by instance",
   "type": "timeseries",
   "description": "This graph shows how IO queue consumption is distributed between io-groups and streams.\n\nscylla_io_queue_consumption",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_io_queue_consumption{iogroup=~\"$iogroup\", class=~\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by (instance, iogroup, stream)",
     "legendFormat": "Group {{iogroup}} {{stream}} {{dc}} {{instance}} "
    }
   ]
  },
  {
   "title": "I/O Group Queue flow ratio",
   "type": "timeseries",
   "description": "This graph shows the ratio of dispatch rate to completion rate. It is expected to be 1.0, growing larger on reactor stalls or disk problems.\n\nscylla_io_queue_flow_ratio",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], scylla_io_queue_flow_ratio{iogroup=~\"$iogroup\", instance=~\"[[node]]\", cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"})",
     "legendFormat": "Group {{iogroup}} {{dc}} {{instance}} {{shard}}"
    }
   ]
  },
  { "title": "$classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "classes" },
  {
   "title": "$classes I/O Queue delay by [[by]]",
   "type": "timeseries",
   "description": "Total time spent in the queue",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], max(rate(scylla_io_queue_total_delay_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])/rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or on() max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$classes Queue length by [[by]]",
   "type": "timeseries",
   "description": "Number of requests in the queue",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], max(scylla_io_queue_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$classes I/O Queue bandwidth by [[by]]",
   "type": "timeseries",
   "description": "The queue bandwidth rate in bytes \n\nscylla_io_queue_total_bytes",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_io_queue_total_bytes{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$classes I/O Queue IOPS by [[by]]",
   "type": "timeseries",
   "description": "The rate of io queue operation\n\nsscylla_io_queue_total_operations",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Disk $classes I/O Queue delay by [[by]]",
   "type": "timeseries",
   "description": "Total time spent in disk",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], max(rate(scylla_io_queue_total_exec_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])/rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or on() max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]]))"
    }
   ]
  },
  {
   "title": "DISK $classes Queue length by [[by]]",
   "type": "timeseries",
   "description": "Number of requests in the disk",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], max(scylla_io_queue_disk_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "DISK $classes starvation time by [[by]]",
   "type": "timeseries",
   "description": "The time the class waited for being dispatched with non-empty software queue.\n\nLarge IO delays coupled with small starvation time denotes that scheduler is doing its job properly, and it's upper layer that overflows disk capacity.\n\nLarge IO delays coupled with large starvation time denotes that there might be some problem on the scheduler level that it cannot deliver IO requests from that class into disk in timely manner or the disk is slow and cannot afford timely dispatching.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_io_queue_starvation_time_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information by Task Group</h1>"
  },
  { "title": "$sg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "sg" },
  {
   "title": "Time used by [[by]] - $sg",
   "type": "timeseries",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. This graph shows how much time was spent in $sg group",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(rate(scylla_scheduler_runtime_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[$__rate_interval])/1000) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Time spent in task quota violations by [[by]] - $sg",
   "type": "timeseries",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. The maximum amount of time during which a task group can run is called the \"task quota\". Some task groups may disrespect that and run for longer. This may cause latency issues",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(rate(scylla_scheduler_time_spent_on_task_quota_violations_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[$__rate_interval])/1000) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Starvation time by [[by]] - $sg",
   "type": "timeseries",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. The maximum amount of time during which a task group can run is called the \"task quota\". Some task groups may disrespect that and run for longer.\n\n This graph shows the amount of time the group was waiting to get CPU time.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(rate(scylla_scheduler_starvetime_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[$__rate_interval])/1000) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Scheduler shares [[by]] - $sg",
   "type": "timeseries",
   "description": "Shares assigned to the $sg. Shares determine how Scylla reactor distributes the task quotas between groups (Higher share gets more quotas)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_scheduler_shares{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  { "title": "Internal node errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Internal node Errors - $cluster</h1>"
  },
  {
   "title": "Local Reads Error by [[by]]",
   "type": "timeseries",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "si:reads/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_storage_proxy_coordinator_read_errors_local_node{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Local Write Error by [[by]]",
   "type": "timeseries",
   "description": "Number of write requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "si:writes/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_storage_proxy_coordinator_write_errors_local_node{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Stall per seconds by [[by]]",
   "type": "timeseries",
   "description": "Number of Stalls per seconds.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_stall_detector_reported{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Reads Unavailable Error by [[by]]",
   "type": "timeseries",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "si:reads/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_storage_proxy_coordinator_read_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Write Unavailable Error by [[by]]",
   "type": "timeseries",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "si:writes/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_storage_proxy_coordinator_write_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Range Unavailable Error by [[by]]",
   "type": "timeseries",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_storage_proxy_coordinator_range_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "AIO Error by [[by]]",
   "type": "timeseries",
   "description": "Number of AIO Errors",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], avg(rate(scylla_reactor_aio_errors{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Ignored Future By [[by]]",
   "type": "timeseries",
   "description": "Total number of abandoned failed futures, futures destroyed while still containing an exception.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_reactor_abandoned_failed_futures{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "C++ Exceptions [[by]]",
   "type": "timeseries",
   "description": "Number of C++ exceptions thrown.\n\n An exception by itself does not indicate a problem",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], sum(rate(scylla_reactor_cpp_exceptions{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  { "title": "Commit Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 58 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Commit log Information</h1>"
  },
  {
   "title": "$func reserved disk space by [[by]]",
   "type": "timeseries",
   "description": "Holds the size of disk space in bytes reserved for data so far. A too high value indicates that we have some bottleneck in the writing to sstables path",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_disk_total_bytes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func used disk space by [[by]]",
   "type": "timeseries",
   "description": "Holds the size of disk space in bytes used for data so far. A too high value indicates that we have some bottleneck in the writing to sstables path",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_disk_active_bytes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func flush by [[by]]",
   "type": "timeseries",
   "description": "Counts a number of times the flush() method was called for a file",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(rate(scylla_commitlog_flush{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func Segments by [[by]]",
   "type": "timeseries",
   "description": "Holds the current number of commit log segments",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func flush limit exceeded by [[by]]",
   "type": "timeseries",
   "description": "Counts a number of times a flush limit was exceeded. A non-zero value indicates that there are too many pending flush operations (see pending_flushes) and some of them will be blocked till the total amount of pending flush operations drops below 5.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(rate(scylla_commitlog_flush_limit_exceeded{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func Pending allocations by [[by]]",
   "type": "timeseries",
   "description": "Holds the number of currently pending allocations. A non-zero value indicates that we have a bottleneck in the disk write flow.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_pending_allocations{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func Pending flush by [[by]]",
   "type": "timeseries",
   "description": "Counts a number of requests blocked due to memory pressure. A non-zero value indicates that the commitlog memory quota is not enough to serve the required amount of requests.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_pending_flushes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func Unused segments by [[by]]",
   "type": "timeseries",
   "description": "Holds the current number of unused segments. A non-zero value indicates that the disk write path became temporary slow.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_unused_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$func Allocating segments by [[by]]",
   "type": "timeseries",
   "description": "Holds the number of not closed segments that still have some free space. This value should not get too high.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$topbottom([[filter_limit]], $func(scylla_commitlog_allocating_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "RPC metrics - $domain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "domain",
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Client count by [[by]]",
     "type": "timeseries",
     "description": "scylla_rpc_client_count",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(scylla_rpc_client_count{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}) by ([[by]], domain)>0)"
      }
     ]
    },
    {
     "title": "RPC sent messages by [[by]]",
     "type": "timeseries",
     "description": "scylla_rpc_client_sent_messages",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(rate(scylla_rpc_client_sent_messages{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}[$__rate_interval])>0) by ([[by]],domain))"
      }
     ]
    },
    {
     "title": "RPC replied messages by [[by]]",
     "type": "timeseries",
     "description": "scylla_rpc_client_replied",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(rate(scylla_rpc_client_replied{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}[$__rate_interval])>0) by ([[by]],domain))"
      }
     ]
    },
    {
     "title": "RPC exceptional replied messages by [[by]]",
     "type": "timeseries",
     "description": "scylla_rpc_client_exception_received",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(rate(scylla_rpc_client_exception_received{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}[$__rate_interval])>0) by ([[by]],domain))"
      }
     ]
    },
    {
     "title": "RPC requests timeout by [[by]]",
     "type": "timeseries",
     "description": "scylla_rpc_client_timeout",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(rate(scylla_rpc_client_timeout{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}[$__rate_interval])>0) by ([[by]],domain))"
      }
     ]
    },
    {
     "title": "RPC Pending Messages by [[by]]",
     "type": "timeseries",
     "description": "the number of requests queued for sending, but not yet sent\n\nscylla_rpc_client_pending",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(scylla_rpc_client_pending{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}) by ([[by]],domain)>0)"
      }
     ]
    },
    {
     "title": "RPC Wait for Reply by [[by]]",
     "type": "timeseries",
     "description": "the number of requests waiting for the reply\n\nscylla_rpc_client_wait_reply",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(scylla_rpc_client_wait_reply{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}) by ([[by]],domain)>0)"
      }
     ]
    },
    {
     "title": "RPC Delay [[by]]",
     "type": "timeseries",
     "description": "The total time it takes an RPC message to travel back and forth between verb caller and server.\n\nscylla_rpc_client_delay_samples",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "$topbottom([[filter_limit]], sum(rate(scylla_rpc_client_delay_samples{instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\", domain=\"$domain\"}[$__rate_interval])>0) by ([[by]],domain))"
      }
     ]
    }
   ]
  },
  { "title": "Your panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Your Panels</h1>"
   }
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } }
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "<div style=\"color:#5780C1; border-bottom: 0px solid #5780C1;\">Scylla Monitoring version - 4.12.1</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1600&height=-1&kiosk\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div>"
   }
  }
 ]
}