apiVersion: scylla.scylladb.com/v2
kind: ScyllaCluster
metadata:
  name: scylla
spec:
  agentVersion: 4.5.0@sha256:12755969f1b3258572c520aa82c2f18db52287b3dc7055a977072284f234da16
  version: 2026.1.2
  automaticOrphanedNodeCleanup: true
  sysctls:
    - fs.aio-max-nr=30000001
  datacenter:
    name: dc2
    racks:
      - name: dc2-r1
        members: 4
        storage:
          capacity: 51Gi
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: 7
            memory: 65Gi
          limits:
            cpu: 7
            memory: 65Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
