apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-manager-cluster
  namespace: scylla-manager
spec:
  version: 6.2.0
  agentVersion: 3.4.0@sha256:441403aed8880cad1feef68aa7a8ee9ffd99a458dc1dcff3dc54ce5bf3cb07b7
  repository: docker.io/scylladb/scylla
  agentRepository: docker.io/scylladb/scylla-manager-agent
  developerMode: true
  cpuset: false
  sysctls:
    - fs.aio-max-nr=30000000
  datacenter:
    name: manager-dc
    racks:
      - members: 1
        name: manager-rack
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 100Mi
        storage:
          capacity: 5Gi
          storageClassName: scylladb-local-xfs
